name: "Test"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  phpstan:
    name: PHPStan static analysis

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 8.1

    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: "${{ matrix.php-version }}"

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install the composer dependencies
        uses: php-actions/composer@v1

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

  psalm:
    name: Psalm static analysis

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 8.1

    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: "${{ matrix.php-version }}"

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install the composer dependencies
        uses: php-actions/composer@v1

      - name: Run static analysis
        run: vendor/bin/psalm --show-info=true --shepherd

  standards:
    name: PHP-CS-Fixer coding standards

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 8.1

    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: "${{ matrix.php-version }}"

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install the composer dependencies
        uses: php-actions/composer@v1

      - name: Check the coding standards
        run: vendor/bin/php-cs-fixer fix --dry-run -v

  unit:
    name: PHPUnit unit tests

    runs-on: ubuntu-latest

# #todo remove unused versions in project
    strategy:
      matrix:
        php-version:
          - 7.4
          - 8.0
          - 8.1

    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: "${{ matrix.php-version }}"

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install the composer dependencies
        uses: php-actions/composer@v1

      - name: Run the unit tests
        run: vendor/bin/phpunit
